---
title: "plot_ak_frp_data"
output: html_notebook
---
```{r, echo=FALSE, warning=FALSE}
########################################################################### #
#
# plot_ak_frp_data.R 
#
# Objective:  Plot processed MxD14A1 FRP data.
#
# Input:     .RData file produced by process_ak_frp_data.R
#
# Output:     Box-plots of FRP by burn frequency (1x, 2x, 3x burns)
#             
#   
#   JWalker 17 April 2018
#  
########################################################################### #

# ---- Set environment ----

# Remove existing data and values
rm(list=ls())

# Load libraries
library(ggplot2)
library(lubridate)

# Set folder paths
path.in <- "D:/projects/ak_fire" 
path.plots <- "D:/projects/ak_fire/output/plots/frp"

# Load functions
source(file.path(path.in, "R", "ak_functions.R"))

# Load data saved from 'process_ak_frp_data.R'
rdata <- "ak_frp_data.RData"
load(file = file.path(path.in, "data", rdata))

# Set consistent plot parameters
dodge = position_dodge(0.16)
theme_set(theme_bw())
plot_opts <- theme(panel.grid.minor.x = element_blank(),
                   panel.grid.major.x = element_blank(), # hide gridlines
                   legend.key = element_blank(),  # remove boxes around legend items
                   plot.title = element_text(hjust = 0.5)) # center title
```
## Boxplot by burn number

```{r}
title <- "FRP by burn number, all years, combined land cover"
plot.name <- "AK_FRP by burn number_all years.png"

# Get means
means <- aggregate(MaxFRP ~ burn_num, x, mean)

# Plot boxplot with mean values 
p <- ggplot(x, aes(as.factor(burn_num), MaxFRP)) + 
            geom_boxplot(aes(fill = as.factor(burn_num)), show.legend = F) +
            geom_point(data=x.frp.summary, aes(as.factor(burn_num), avg, shape = "avg"), size = 7) +
            scale_shape_manual("", values = 18) +
            geom_text(data = means, aes(label = round(MaxFRP, 2), y = MaxFRP + 16), hjust = -0.2) +
            coord_cartesian(ylim = c(0,500), expand = TRUE) +
            labs(x = "Burn number", y = "FRP") +
            ggtitle(title)
p + plot_opts
```


