# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# add_rasters.py
# Created on: 2017-04-11 12:47:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
grdyr185_86 = "D:\\projects\\LCMAP\\data\\class6_2\\x1985_1986\\grdyr185_86"
grdyr186_87 = "D:\\projects\\LCMAP\\data\\class6_2\\x1986_1987\\grdyr186_87"
grdyr187_88 = "D:\\projects\\LCMAP\\data\\class6_2\\x1987_1988\\grdyr187_88"
grdyr188_89 = "D:\\projects\\LCMAP\\data\\class6_2\\x1988_1989\\grdyr188_89"
rastercalc4 = "C:\\Users\\jjwalker\\Documents\\ArcGIS\\Default.gdb\\rastercalc4"

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("\"%grdyr185_86%\" + \"%grdyr186_87%\" + \"%grdyr187_88%\" + \"%grdyr188_89%\"", rastercalc4)

