# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# tabulate_ecoregions.py
# Created on: 2017-02-13 13:34:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.CheckExtension('Spatial')
arcpy.CheckOutExtension('Spatial')


# Local variables:
polys = "D:\\projects\\Fire_AK_reburn\\data\\firePerimeters_1940_2016_individual_polys.shp"
akecoregions = "J:\\Base_data\\Boundaries\\ecoregions\\akecoregions.shp"
tabAreas_level1 = "D:\\projects\\Fire_AK_reburn\\data\\firePerimeters_1940_2016_akecoregions_lvl1.dbf"
tabAreas_level2 = "D:\\projects\\Fire_AK_reburn\\data\\firePerimeters_1940_2016_akecoregions_lvl2.dbf"

# Tabulate areas for level 1 classifications
arcpy.gp.TabulateArea_sa(polys, "FID", akecoregions, "LEVEL_1", tabAreas_level1, "30")
print "Ecoregions level 1 complete"

# Tabulate areas for level 2 classifications
arcpy.gp.TabulateArea_sa(polys, "FID", akecoregions, "LEVEL_2", tabAreas_level2, "30")
print "Ecoregions level 2 complete"

arcpy.CheckInExtension('Spatial')